#!/bin/bash
# control scripts for 'check_chef_test_suite' component

if [ -z "$SCRIPT" ] || [ -z "$MYUSER" ] || [ -z "$MYBASE" ]; then
  echo "error!  you must run components via the pfcontrol wrapper!" >&2
  exit 1
fi

check_chef_test_suite_valid_monitor() {
  
  if [[ `grep Ubuntu /etc/issue` ]]; then
    return 0
  else
    return 1
  fi
}

check_chef_test_suite_alerts() {
  
  # How many attempted Chef client runs are in the log file?
  RUN_ATTEMPTS=`egrep -c '\] INFO: \*\*\* Chef ' /var/log/chef/client.log`
  
  # If the log file is missing, fail straight away
  if [ ! -f "/var/log/chef/client.log" ]; then
    add_alert "chef_client_log_missing" 2
  
  # If there are less than two attempted Chef client runs in the log file, 
  # it's possible we won't have a skips line to look for, which would cause 
  # false alerts
  elif [[ $RUN_ATTEMPTS -lt 2 ]]; then
    add_alert "chef_client_test_suite_stale" 0
    add_alert "chef_client_test_suite_failure" 0
    
  else
    
    # First, check if the most recent execution of the test suite was within the last hour
    DATE_STRING=`grep -A1 skips /var/log/chef/client.log | tail -1 | cut -d '[' -f 2 | cut -d ']' -f 1 | sed 's/T/ /g'`
    
    REGEX="^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\+[0-9]{2}:[0-9]{2}$"
    if [[ $DATE_STRING =~ $REGEX ]]; then
    	DATE=`date -d "$DATE_STRING" +%s`
    else
    	DATE=0
    fi
    
    NOW=`date +%s`
    DIFF=$(($NOW - $DATE))
    
    if [[ $DIFF -gt 3600 ]]; then
        RC=2
    else
        RC=0
    fi
    
    add_alert "chef_client_test_suite_stale" $RC
    
    # Secondly, check that the test suite executed without any failures or errors
    TEST_SUITE_OUTPUT=`grep skips /var/log/chef/client.log | tail -1`
    
    REGEX=", 0 failures, 0 errors, "
    if [[ $TEST_SUITE_OUTPUT =~ $REGEX ]]; then
      RC=0
    else
      RC=2
    fi
    
    add_alert "chef_client_test_suite_failure" $RC
  fi
}
