#!/bin/bash
# control scripts for 'check_4_gautrigger' monitor - mawalsh
# Checks for the existence of the GAU game trigger on all master & readslaves.  IT SHOUDLN'T EXIST!
#


if [ -z "$SCRIPT" ] || [ -z "$MYUSER" ] || [ -z "$MYBASE" ]; then
  echo "error!  you must run components via the pfcontrol wrapper!" >&2
  exit 1
fi

check_4_gautrigger_valid_monitor() {
 
  CHECK_HOSTNAME=`hostname | egrep "dbu[0-9]{2,3}(m|r1)$"`
  if [ -z "$CHECK_HOSTNAME" ]
  then
	return 1
  fi
  return 0

}

check_4_gautrigger_alerts() {

  RETURNC=0
  local MSG
  CHKOBJ=`/usr/bin/mysql information_schema -u root -s -N -e "select count(*) from TRIGGERS where TRIGGER_NAME='GAUCHECK_UPDATE';"`
  RC0=$?

  if [ $RC0 -eq 0 ]
  then
	if [[ "$CHKOBJ" -eq "1" ]]
        then
                        MSG="GAU trigger exists! Remove immediately as should only exist on slave"
                        RETURNC=2
	fi
  else
	MSG="SQL_checks_failing"
	RETURNC=1
  fi

  ## Output results to pfcontrol
  add_alert "check_4_gautrigger" $RETURNC $MSG
  ##echo "check_4_gautrigger" $RETURNC $MSG

}
