#! /usr/bin/perl -w
#
# check_mem v1.5 plugin for nagios
#
# uses the output of `free` to find the percentage of memory used
#
# Copyright Notice: GPL
#
# History:
#
# v.1.6  Santiago Velasco - Added Swap Check Thresholds (-W -C)
#
# v1.5.1 Javier Cubero - tweaked check to ignore buffers
#
# v1.5 Rouven Homann - rouven.homann@cimt-ag.de
#	+ perfomance tweak with free -mt (just one sub process started instead of 7)
#	+ more code cleanup
#
# v1.4 Garrett Honeycutt - gh@3gupload.com
#	+ Fixed PerfData output to adhere to standards and show crit/warn values
#
# v1.3 Rouven Homann - rouven.homann@cimt-ag.de
# 	+ Memory installed, used and free displayed in verbose mode
#	+ Bit Code Cleanup
#
# v1.2 Rouven Homann - rouven.homann@cimt-ag.de
#	+ Bug fixed where verbose output was required (nrpe2)
#       + Bug fixed where perfomance data was not displayed at verbose output
#	+ FindBin Module used for the nagios plugin path of the utils.pm
#
# v1.1 Rouven Homann - rouven.homann@cimt-ag.de
#    	+ Status Support (-c, -w)
#	+ Syntax Help Informations (-h)
#       + Version Informations Output (-V)
#	+ Verbose Output (-v)
#       + Better Error Code Output (as described in plugin guideline)
#
# v1.0 Garrett Honeycutt - gh@3gupload.com
# 	+ Initial Release
# 
use strict;
use FindBin;
use lib $FindBin::Bin;
use utils qw($TIMEOUT %ERRORS &print_revision &support);
use vars qw($PROGNAME $PROGVER);
use Getopt::Long;
use vars qw($opt_V $opt_h $verbose $opt_w $opt_c $opt_sw $opt_sc);

$PROGNAME = "check_mem";
$PROGVER = "1.5.1";

sub print_help ();
sub print_usage ();

Getopt::Long::Configure('bundling');
GetOptions ("V"   => \$opt_V, "version"    => \$opt_V,
	"h"   => \$opt_h, "help"       => \$opt_h,
        "v" => \$verbose, "verbose"  => \$verbose,
	"w=s" => \$opt_w, "warning=s"  => \$opt_w,
	"W=s" => \$opt_sw, "swap-warning=s"  => \$opt_sw,
        "C=s" => \$opt_sc, "swap-critical=s"  => \$opt_sc,
	"c=s" => \$opt_c, "critical=s" => \$opt_c);

if ($opt_V) {
    print_revision($PROGNAME,'$Revision: '.$PROGVER.' $'); 
    exit $ERRORS{'UNKNOWN'};
}

if ($opt_h) {
     print_help();
    exit $ERRORS{'UNKNOWN'};
}

print_usage() unless (($opt_c) && ($opt_w));

my $critical = $1 if ($opt_c =~ /([0-9]+)/);
my $warning = $1 if ($opt_w =~ /([0-9]+)/);
my $s_critical = $1 if ($opt_sc =~ /([0-9]+)/);
my $s_warning = $1 if ($opt_sw =~ /([0-9]+)/);

my $verbose = $verbose;
 
my ($mem_percent, $mem_total, $mem_used, $swap_percent, $swap_total, $swap_free ) = &sys_stats();
my $mem_free = $mem_total - $mem_used;
my $swap_used = $swap_total - $swap_free;
if($opt_c && $opt_w && $opt_sw && $opt_sc){
	if ($swap_percent>$s_critical) {
	    print "CRITICAL: $mem_percent\% Used Memory - $swap_percent\% Swap Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;SwapUsed=$swap_used;SwapFree=$swap_free;SwapTotal=$swap_total\n";
	    exit $ERRORS{'CRITICAL'};
	} elsif ($swap_percent>$s_warning) {
	    print "WARNING: $mem_percent\% Used Memory - $swap_percent\% Swap Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;SwapUsed=$swap_used;SwapFree=$swap_free;SwapTotal=$swap_total\n";
	    exit $ERRORS{'WARNING'};
	}elsif ($mem_percent>$critical) {
	    print "CRITICAL: $mem_percent\% Used Memory - $swap_percent\% Swap Memory  | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;SwapUsed=$swap_used;SwapFree=$swap_free;SwapTotal=$swap_total\n";
	    exit $ERRORS{'CRITICAL'};
	} elsif ($mem_percent>$warning) {
	    print "WARNING: $mem_percent\% Used Memory - $swap_percent\% Swap Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;SwapUsed=$swap_used;SwapFree=$swap_free;SwapTotal=$swap_total\n";
	    exit $ERRORS{'WARNING'};
	}else {
	    print "OK: $mem_percent\% Used Memory - $swap_percent\% Swap Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;SwapUsed=$swap_used;SwapFree=$swap_free;SwapTotal=$swap_total\n";
	    exit $ERRORS{'OK'};
	}
}
elsif ($mem_percent>$critical) {
    print "CRITICAL: $mem_percent\% Used Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total;\n"; 
    exit $ERRORS{'CRITICAL'};
} elsif ($mem_percent>$warning) {
    print "WARNING: $mem_percent\% Used Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total\n";
    exit $ERRORS{'WARNING'};
} else {
    print "OK: $mem_percent\% Used Memory | MemUsed=$mem_used;MemFree=$mem_free;MemTotal=$mem_total\n"; 
    exit $ERRORS{'OK'};
}

sub sys_stats {
    my @memory = split(" ", `free -mt`);

    my $swap_total = $memory[18];
    my $swap_free = $memory[20];
#    my $mem_total = $memory[22];
#    my $mem_used = $memory[23];
#    my $mem_total = $memory[7] + $memory[15] + $memory[16];
#    my $mem_used = $memory[8] + $memory[15];
#    my $mem_percent = (($mem_used + $free_swap) / ($mem_total + $swap_total)) * 100;

    my $mem_total = $memory[7];
    my $mem_used = $memory[15];
    my $mem_percent = ($mem_used / $mem_total) * 100;

    my $swap_percent = ( ($swap_total - $swap_free) / $swap_total ) * 100;
    return (sprintf("%.0f",$mem_percent),$mem_total,$mem_used,sprintf("%.0f",$swap_percent),$swap_total,$swap_free);
}
			
sub print_usage () {
    print "Usage: $PROGNAME -w <warn> -c <crit> -W <swap warn> -C <swap crit> [-v] [-h] \n";
    exit $ERRORS{'UNKNOWN'} unless ($opt_h);
}
				
sub print_help () {
    print_revision($PROGNAME,'$Revision: '.$PROGVER.' $');
    print "Copyright (c) 2005 Garrett Honeycutt/Rouven Homann\n";
    print "\n";
    print_usage();
    print "\n";
    print "-w <warn> = Memory usage to activate a warning message.\n";
    print "-c <crit> = Memory usage to activate a critical message.\n";
    print "-v = Verbose Output.\n";
    print "-h = This screen.\n\n";
    support();
}
